Fixed Program not running due to using statement.
Currently getting the error:
SqlException: Invalid column name 'Discriminator'.

When trying to register.